thisOS=`uname`
# we want to append this file after oh-my-zsh installed
# cp .zshrc ~/.zshrc
# cp -r .oh-my-zsh ~/
echo "configure git global"
git config --global color.ui auto
git config --global core.editor vim
git config --global merge.tool vimdiff

if ! [ "$thisOS" == "Darwin" ]; then
    echo Linux system detected!
    sudo apt-get install zsh 
    echo "installing command-not-found for zsh..."
    sudo apt-get install command-not-found
	sudo apt-get install tmux 
	sudo apt-get install vim 
else
    echo Mac OS system detected
	brew install zsh
    brew install tmux
    brew install wget
    brew install vim

    echo install iterm 2
    wget https://iterm2.com/downloads/stable/iTerm2_v2_0.zip
    unzip iTerm2_v2_0.zip
    sudo cp -r iTerm.app /Applications
fi

#check if need to change shell to zsh
needChange=$(echo $0 | grep "zsh")
if [ -z "$needChange" ]; then
    echo "trying to change to zsh at `which zsh`"
    chsh -s `which zsh`
    echo "If no error found above, please log out and relogin to use zsh"
fi

cp -r .vim ~/
cp .vimrc ~/.vimrc
cp .tmux.conf ~/
echo Installing oh-my-zsh...
curl -L http://install.ohmyz.sh | sh

# check if need to append our .zshrc to one generated by oh-my-zsh
alreadyAppen=$(cat ~/.zshrc | grep "Hello World, this")
if [ -z "$alreadyAppen" ]; then
    echo Append our .zshrc to oh-my-zshs one
    cat .zshrc >> ~/.zshrc
fi


